@startuml
package negocio {
package mecánicas {

interface Desplazable {
    +{abstract}moverse()
}

class Control {
    - teclaSuperior: boolean
    - teclaInferior: boolean
    - teclaDerecha: boolean
    - teclaIzquierda: boolean
}

}

package escenario {
class Tablero {
    -generarBloques()
}
}
package bloques {

abstract class Bloque {
}

class BloqueDeHielo {
    +romper()
}

class BloqueEstático {}
}
package frutas {
    abstract class Fruta {
        -puntuación: int
    }

    class Banana {

    }
}

package nivel {

class Nivel {
   -número: int
   -completado: boolean
   -generarPersonajes()
   -generarFrutas()
   -generarTablero(int tamanioEnX, int tamanioEnY   )
}

}

package personajes {
    abstract class Entidad {
        +{abstract}destruirBloque()
    }

    class Jugador {
        - puntuación: int
        +generarBloque()
        +recolectarFruta()
        +morir()
    }

class Enemigo {
        +atraparJugador()
    }

 class VacaLoca {
    }

}
class BadIceCream {
    +empezar()
    +elegirNivel()
    +cerrar()
}
}

BadIceCream ..> nivel

Nivel --> "1..n" Enemigo
Nivel --> "1" Jugador
Nivel --> Fruta
frutas ..> mecánicas
personajes ..> mecánicas

Jugador -up-|> Entidad
Enemigo -up-|> Entidad
VacaLoca -up-|> Enemigo
Banana -up-|> Fruta
Tablero --> "*" Bloque
BloqueDeHielo -up-|> Bloque
BloqueEstático -up-|> Bloque
Jugador -> Control
Nivel --> Tablero

}

@enduml