@startuml
package negocio {
package mecánicas {
    class Control {
    -espacio: Tecla
    -p: Tecla
    -enter: Tecla
    }
    enum Dirección {
    ARRIBA
    ABAJO
    IZQUIERDA
    DERECHA
    }
    class ColocadorDeObjetos {}
    class Colisión {}
}

package escenario {
    class Tablero {}

package bloques {
    abstract class Bloque {}
    class BloqueDeHielo {}
    class BloqueEstático {}
}

package Entidades {
    abstract class Entidad {
    -posX: int
    -posY: int
    -velocidad: int
    }
    class Jugador {
    -puntación: int
    +generarODestruirBloque()
    +recolectarFruta()
    }
package enemigos {
    abstract class Enemigo {}
    class Toro {}
    class Ogro {}
}

package frutas {
    abstract class Fruta {}
    class Mora {}
}
}
}
class BadIceCream {
    +empezar()
    +cargar()
    +cerrar()
}
}

BadIceCream --> Tablero
Tablero --> "*" Entidad
Bloque <|-- BloqueEstático
Bloque <|-- BloqueDeHielo
Tablero --> "*" Bloque

Entidad <|-down-Jugador
Entidad <|-down--Enemigo
Entidad <|-up- Fruta
Fruta <|- Mora
Enemigo <|-- Toro
Enemigo <|-- Ogro

Control --> Dirección
Entidad --> Control
Entidad --> ColocadorDeObjetos
Entidad --> Colisión

@enduml